- name: Install monit
  apt: pkg=monit state=installed

- name: Copy monit master config file into place
  copy: src=etc_monit_monitrc dest=/etc/monit/monitrc
  notify: restart monit

- name: Copy monit service config files into place
  copy: src=etc_monit_conf.d_{{ item }} dest=/etc/monit/conf.d/{{ item }}
  with_items:
    - sshd
    - pdnsd
    - pptpd
    - squid3
  notify: restart monit
